name: article_downloader_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Or your preferred Python version
  - pandas
  - requests
  - jinaai # Or jina, if you prefer the original Jina library
  - beautifulsoup4
  - html2text
  - scikit-learn
  - python-dotenv
  - tqdm
  - pydantic-settings
  - pyyaml
  - aiohttp
  - requests-cache
  - diskcache
  - pytest
  - requests-mock
  - responses
  - ipykernel # To run IPython Notebooks in this environment
  - notebook   # To run Jupyter Notebook