# Language: YAML
name: tsi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - numpy
  - pandas
  - requests
  - beautifulsoup4
  - html2text
  - scikit-learn
  - python-dotenv
  - tqdm
  - pydantic-settings
  - pyyaml
  - aiohttp
  - requests-cache
  - diskcache
  - pytest
  - requests-mock
  - responses
  - ipykernel
  - notebook
  - hdbscan
  - pyarrow
  - matplotlib
  - seaborn
  - jinaai
  - google-generativeai