name: tsi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - numpy
  - pandas
  - requests
  - beautifulsoup4
  - html2text
  - scikit-learn
  - python-dotenv
  - tqdm
  - pydantic-settings
  - pyyaml
  - pytest
  - requests-mock
  - responses
  - ipykernel
  - notebook
  - matplotlib
  - seaborn
  - pip
  - pip:
      - google-generativeai