name: tsi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - cryptography        # remove strict version pin
  - zstd                # remove strict version pin; conda will pick a compatible build
  - zlib                # maybe leave the default build or pin to a version if needed
  - sqlite              # remove the explicit version so that conda picks one
  - numpy=2.2.2         # keep if needed, or consider unpinning
  - hdbscan
  - protobuf
  - pyarrow
  - aiohappyeyeballs
  - aiosignal
  - anyio
  - appnope            # macOS-specific; you might remove on Linux if not needed
  - argon2-cffi-bindings=21.2.0
  - argon2-cffi
  - arrow=1.3.0
  - async-lru
  - asttokens
  - attrs=25.1.0
  # ... include additional core packages here ...
  - pytest=8.3.4
  - python-dotenv=1.0.1
  - pyyaml=6.0.2
  # Remove/adjust packages that are reported as “does not exist”
  # For example, remove:
  #   - cline
  #   - pyobjc-core
  #   - pyobjc-framework-cocoa
  #   - google-api-client  (use google-api-python-client if needed)
  #   - jupyter-client, jupyter-events, jupyter-server-terminals, jupyter-server, jupyterlab-server, jupyterlab-widgets (verify names)